import { onPageReady } from './utils/lifecycle';

// Loaded once per document and cached — ClientRouter view transitions swap
// the DOM but keep this module alive, so re-fetching the script on every
// navigation would be wasted work.
let pagefindScript: Promise<void> | undefined;

function loadPagefindScript(): Promise<void> {
  if (!pagefindScript) {
    pagefindScript = new Promise((resolve, reject) => {
      // Generated by the `pagefind` build step (package.json) into
      // dist/pagefind/ — this 404s under `astro dev`, where that directory
      // doesn't exist. Test search with `npm run build && npm run preview`.
      const script = document.createElement('script');
      script.src = '/pagefind/pagefind-ui.js';
      script.onload = () => resolve();
      script.onerror = () => reject(new Error('Failed to load pagefind-ui.js'));
      document.head.appendChild(script);
    });
  }
  return pagefindScript;
}

function bindSiteSearch() {
  const trigger = document.getElementById('site-search-trigger');
  const dialog = document.getElementById('site-search-dialog');
  const closeBtn = document.getElementById('site-search-close');
  const results = document.getElementById('site-search-results');
  if (
    !(trigger instanceof HTMLButtonElement) ||
    !(dialog instanceof HTMLDialogElement) ||
    !(closeBtn instanceof HTMLButtonElement) ||
    !results
  ) {
    return;
  }

  trigger.addEventListener('click', async () => {
    dialog.showModal();
    try {
      await loadPagefindScript();
      // A view transition remounts this dialog with a fresh (empty) results
      // element, so re-checking childElementCount (rather than a one-time
      // "already initialized" flag) naturally re-inits PagefindUI once per
      // mount instead of skipping it after the first page.
      if (results.childElementCount === 0) {
        // @ts-expect-error — global set by the dynamically loaded pagefind-ui.js; no types shipped for it
        new window.PagefindUI({ element: results, showSubResults: true, showImages: false });
      }
      results.querySelector('input')?.focus();
    } catch {
      if (results.childElementCount === 0) {
        results.textContent = "Search isn't available right now — try again in a moment.";
      }
    }
  });

  closeBtn.addEventListener('click', () => dialog.close());
  dialog.addEventListener('click', (event) => {
    if (event.target === dialog) dialog.close();
  });
}

export function initSiteSearch(): void {
  onPageReady(bindSiteSearch);
}
